### ISSUE TITLE
Support same named page config files, e.g. `pages/index.page.js` & `foo/index.page.js`.

### ISSUE THREAD

**Issue by brillout** [reframejs/goldpage#3]
As pointed by @chriscalo in https://github.com/reframejs/goldpage/issues/2.

**Comment by chriscalo** [comment]
Copying what I said in #2 here to save some back-and-forth:

I like structuring files in web apps in a way that matches URL paths. However, goldpage yells at me when more than one page config file has the same name. Here's how I prefer to structure things, but this doesn't work with goldpage because there are two index.page.js files (even though they're in different folders):

``` text
/ => pages/index.page.js
/foo => pages/foo/index.page.js
```

**Comment by brillout** [comment]
Done & published in new version `0.5.2`.

**Comment by chriscalo** [comment]
Seems to work great, thanks so much 🙏
